WINDOW_WIDTH = love.graphics.getWidth()
WINDOW_HEIGHT = love.graphics.getHeight()
ORIGIN_WINDOW_WIDTH = love.graphics.getWidth()
ORIGIN_WINDOW_HEIGHT = love.graphics.getHeight()


OBJ_TYPE_HERO  = 0x00000001
OBJ_TYPE_BOT   = 0x00000002
OBJ_TYPE_STUFF = 0x00000004

DRAW_LAYER_BG     = 1
DRAW_LAYER_BULLET = 2
DRAW_LAYER_BOT    = 3
DRAW_LAYER_USER   = 4
DRAW_LAYER_GUI    = 5
DRAW_LAYERS_COUNT = DRAW_LAYER_GUI

LOG_SURFACE = 1
LOG_BASE    = 2
LOG_DEEP    = 3

LOG_LEVEL = LOG_DEEP


grid_layers = 
{
  DRAW_LAYER_BG,
  DRAW_LAYER_BULLET,
  DRAW_LAYER_BOT,
  DRAW_LAYER_USER,
}